name: china-city-mass-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  
  # Core data processing
  - pandas>=1.5.0
  - numpy>=1.21.0
  - geopandas>=0.12.0
  - shapely>=1.8.0
  
  # Geospatial processing
  - rasterio>=1.3.0
  - fiona>=1.8.0
  - pyproj>=3.4.0
  
  # Statistical analysis
  - statsmodels>=0.13.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Utilities
  - tqdm>=4.64.0
  - requests>=2.28.0
  - python-dateutil>=2.8.0
  
  # Optional scientific packages
  - xarray>=2022.6.0
  - netcdf4>=1.6.0
  
  # Jupyter support
  - jupyter>=1.0.0
  - ipywidgets>=8.0.0
  
  # Pip dependencies (packages not available on conda-forge)
  - pip:
    - earthengine-api>=0.1.350
    - geemap>=0.21.0
    - exactextract>=0.1.0
    - h3>=3.7.0
    - tobler>=0.8.0
    - folium>=0.14.0
    - plotly>=5.10.0
    - powerlaw>=1.4.0