name: china-city-mass-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - geopandas>=0.12.0
  - shapely>=1.8.0
  - fiona>=1.8.0
  - pyproj>=3.4.0
  - rasterio>=1.3.0
  - h3-py>=3.7.0
  - statsmodels>=0.13.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - folium>=0.14.0
  - matplotlib>=3.6.0
  - seaborn>=0.11.0
  - tqdm>=4.64.0
  - jupyter>=1.0.0
  - pytest>=7.0.0
  - pip
  - pip:
    - earthengine-api>=0.1.350
    - geemap>=0.20.0
    - tobler>=0.9.0
    - exactextract>=0.15.0
    - plotly>=5.11.0
    - ipywidgets>=8.0.0